export const imageData = [
    {
      image:
        'https://www.juet.ac.in/images/show/12.jpg'
    },
    {
      image:
        'https://www.juet.ac.in/images/show/33.jpg'
    },
    {
      image:
        'https://www.juet.ac.in/images/show/16.jpg'
    },
    {
      image:
        'https://www.juet.ac.in/images/show/4.jpg'
    },
    {
      image:
        'https://www.juet.ac.in/images/show/1.jpg'
    }
  ];